version: '3.8'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: advisory_performance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "5432:5432"
    networks:
      - advisory-etl-network

  backend:
    build: ./backend
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: advisory_performance
      DB_USERNAME: postgres
      DB_PASSWORD: password
      FLASK_ENV: production
    depends_on:
      - database
    ports:
      - "5000:5000"
    networks:
      - advisory-etl-network
    volumes:
      - ./backend/logs:/app/logs

  frontend:
    build: ./frontend
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - advisory-etl-network

volumes:
  postgres_data:

networks:
  advisory-etl-network:
    driver: bridge
